---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[chef-varnish::default]
    attributes:
  - name: nagios-plugin
    run_list:
      - recipe[chef-varnish::default]
      - recipe[chef-varnish::nagios-plugin]
    attributes:
