Metrics/LineLength:
  Max: 120

Lint/AmbiguousRegexpLiteral:
  Exclude:
   - test/**/features/**/*.rb
   - tmp/**/test/**/features/**/*.rb

Lint/ParenthesesAsGroupedExpression:
  Exclude:
   - spec/**/*
   - tmp/**/spec/**/*
