source 'https://rubygems.org'

gem 'cucumber',   '~> 1.2.1'
gem 'httparty',   '~> 0.10.0'
gem 'minitest',   '~> 3.0.0'
gem 'nokogiri',   '~> 1.10.8'
gem 'chef',       '~> 11.16.0'
gem 'berkshelf',  '~> 3.0.0'
gem 'chefspec',   '~> 4.2.0'
gem 'foodcritic', '~> 4.0.0'
gem 'rake'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'vagrant-wrapper'
